import { describe, expect, it } from "vitest";

import { runContinuityRuleChecks } from "@/lib/continuity";
import { detectPlotThreadSignal } from "@/lib/story-analysis";
import type { PlotThreadRecord, ProjectWorkspace } from "@/types/storyforge";

function makeProject(): ProjectWorkspace {
  return {
    id: "project-1",
    title: "Continuity Test",
    slug: "continuity-test",
    premise: "A spy tries to survive a siege.",
    oneLineHook: "A Roman spy watches a holy city consume itself.",
    bookSettings: {
      genre: "Historical tragedy",
      tone: "Severe and intimate",
      audience: "Adult",
      themes: ["duty", "guilt"],
      pointOfView: "Third person limited",
      tense: "Past tense",
      targetChapterLength: 3500,
      targetBookLength: 90000,
      storyBrief: "Lucius serves Rome while Jerusalem tears itself apart.",
      plotDirection: "Escalate the siege and Lucius's moral collapse.",
      pacingNotes: "",
      romanceLevel: 0,
      darknessLevel: 8,
      proseStyle: "Concrete and tragic",
      comparableTitles: [],
    },
    styleProfile: {
      guidanceIntensity: "STRONG",
      proseDensity: 5,
      pacing: 5,
      darkness: 8,
      romanceIntensity: 0,
      humorLevel: 0,
      actionFrequency: 5,
      mysteryDensity: 3,
      dialogueDescriptionRatio: 4,
      literaryCommercialBalance: 6,
      aestheticGuide: "",
      styleGuide: "",
      voiceRules: [],
    },
    generationPresets: [],
    characters: [
      {
        id: "lucius",
        name: "Lucius Vitellius",
        role: "Protagonist",
        archetype: "",
        summary: "A Roman spy.",
        goal: "",
        fear: "",
        secret: "",
        wound: "",
        quirks: [],
        notes: "",
        tags: [],
        povEligible: true,
        quickProfile: {
          age: "",
          profession: "",
          placeOfLiving: "",
          accent: "",
          speechPattern: "",
        },
        dossier: {
          basicIdentity: {
            fullName: "Lucius Vitellius",
            nicknames: [],
            age: "",
            dateOfBirth: "",
            gender: "",
            culturalBackground: "",
            nationality: "",
            currentResidence: "",
            placeOfOrigin: "",
            beliefSystem: "",
            maritalStatus: "",
            familyStatus: "",
          },
          lifePosition: {
            profession: "",
            workplace: "",
            roleTitle: "",
            socialClass: "",
            educationLevel: "",
            trainingBackground: "",
            militaryBackground: "",
            criminalRecord: "",
            politicalOrientation: "",
            reputation: "",
          },
          personalityBehavior: {
            coreTraits: [],
            virtues: [],
            flaws: [],
            emotionalTendencies: "",
            socialConfidence: "",
            introExtroStyle: "",
            conflictStyle: "",
            decisionMaking: "",
            projectedImage: "",
            trueNature: "",
            hiddenSelf: "",
            embarrassmentTriggers: "",
            angerTriggers: "",
            comfortSources: "",
            fearTriggers: "",
            coreValues: "",
          },
          motivationStory: {
            shortTermGoal: "",
            longTermGoal: "",
            needVsWant: "",
            internalConflict: "",
            externalConflict: "",
            wound: "",
            secrets: [],
            stakesIfFail: "",
            arcDirection: "",
            storyRole: "",
            relationshipToMainConflict: "",
          },
          speechLanguage: {
            accent: "",
            dialect: "",
            nativeLanguage: "",
            otherLanguages: [],
            fluencyLevels: "",
            formalityLevel: "",
            vocabularyLevel: "",
            educationInSpeech: "",
            sentenceLength: "",
            directness: "",
            pointStyle: "",
            descriptors: [],
            repeatedPhrases: [],
            favoriteExpressions: [],
            swearingLevel: "",
            rhythm: "",
            emotionalShifts: "",
            angrySpeech: "",
            scaredSpeech: "",
            lyingSpeech: "",
            persuasiveSpeech: "",
            superiorSpeech: "",
            inferiorSpeech: "",
            lovedOnesSpeech: "",
            avoidedTopics: "",
            commonMisunderstandings: "",
          },
          bodyPresence: {
            physicalDescription: "",
            build: "",
            clothingStyle: "",
            grooming: "",
            distinguishingFeatures: [],
            posture: "",
            movementStyle: "",
            eyeContact: "",
            habitsTics: [],
            roomEntry: "",
            presenceFeel: "",
          },
          relationshipDynamics: {
            friends: [],
            enemies: [],
            rivals: [],
            loversExes: [],
            family: [],
            mentors: [],
            subordinatesSuperiors: [],
            trustLevels: "",
            hiddenLoyalties: "",
            unspokenTensions: "",
            powerDynamics: "",
          },
          freeTextCore: "",
        },
        currentState: {
          currentKnowledge: "",
          unknowns: "",
          emotionalState: "",
          physicalCondition: "",
          loyalties: "",
          recentChanges: "",
          continuityRisks: "",
          lastMeaningfulAppearance: "",
          lastMeaningfulAppearanceChapter: null,
        },
        customFields: [],
        pinnedFields: [],
      },
      {
        id: "baruch",
        name: "Baruch",
        role: "Informant",
        archetype: "",
        summary: "A street boy informant.",
        goal: "",
        fear: "",
        secret: "",
        wound: "",
        quirks: [],
        notes: "",
        tags: [],
        povEligible: false,
        quickProfile: {
          age: "",
          profession: "",
          placeOfLiving: "",
          accent: "",
          speechPattern: "",
        },
        dossier: {
          basicIdentity: {
            fullName: "Baruch",
            nicknames: [],
            age: "",
            dateOfBirth: "",
            gender: "",
            culturalBackground: "",
            nationality: "",
            currentResidence: "",
            placeOfOrigin: "",
            beliefSystem: "",
            maritalStatus: "",
            familyStatus: "",
          },
          lifePosition: {
            profession: "",
            workplace: "",
            roleTitle: "",
            socialClass: "",
            educationLevel: "",
            trainingBackground: "",
            militaryBackground: "",
            criminalRecord: "",
            politicalOrientation: "",
            reputation: "",
          },
          personalityBehavior: {
            coreTraits: [],
            virtues: [],
            flaws: [],
            emotionalTendencies: "",
            socialConfidence: "",
            introExtroStyle: "",
            conflictStyle: "",
            decisionMaking: "",
            projectedImage: "",
            trueNature: "",
            hiddenSelf: "",
            embarrassmentTriggers: "",
            angerTriggers: "",
            comfortSources: "",
            fearTriggers: "",
            coreValues: "",
          },
          motivationStory: {
            shortTermGoal: "",
            longTermGoal: "",
            needVsWant: "",
            internalConflict: "",
            externalConflict: "",
            wound: "",
            secrets: [],
            stakesIfFail: "",
            arcDirection: "",
            storyRole: "",
            relationshipToMainConflict: "",
          },
          speechLanguage: {
            accent: "",
            dialect: "",
            nativeLanguage: "",
            otherLanguages: [],
            fluencyLevels: "",
            formalityLevel: "",
            vocabularyLevel: "",
            educationInSpeech: "",
            sentenceLength: "",
            directness: "",
            pointStyle: "",
            descriptors: [],
            repeatedPhrases: [],
            favoriteExpressions: [],
            swearingLevel: "",
            rhythm: "",
            emotionalShifts: "",
            angrySpeech: "",
            scaredSpeech: "",
            lyingSpeech: "",
            persuasiveSpeech: "",
            superiorSpeech: "",
            inferiorSpeech: "",
            lovedOnesSpeech: "",
            avoidedTopics: "",
            commonMisunderstandings: "",
          },
          bodyPresence: {
            physicalDescription: "",
            build: "",
            clothingStyle: "",
            grooming: "",
            distinguishingFeatures: [],
            posture: "",
            movementStyle: "",
            eyeContact: "",
            habitsTics: [],
            roomEntry: "",
            presenceFeel: "",
          },
          relationshipDynamics: {
            friends: [],
            enemies: [],
            rivals: [],
            loversExes: [],
            family: [],
            mentors: [],
            subordinatesSuperiors: [],
            trustLevels: "",
            hiddenLoyalties: "",
            unspokenTensions: "",
            powerDynamics: "",
          },
          freeTextCore: "",
        },
        currentState: {
          currentKnowledge: "",
          unknowns: "",
          emotionalState: "",
          physicalCondition: "",
          loyalties: "",
          recentChanges: "",
          continuityRisks: "",
          lastMeaningfulAppearance: "",
          lastMeaningfulAppearanceChapter: null,
        },
        customFields: [],
        pinnedFields: [],
      },
    ],
    relationships: [],
    locations: [],
    factions: [],
    timelineEvents: [],
    plotThreads: [
      {
        id: "ledger-thread",
        title: "Hidden temple ledger",
        summary: "Lucius and Baruch hide a temple ledger in a cistern.",
        status: "ACTIVE",
        heat: 4,
        promisedPayoff: "Recover the ledger before the Romans seize it.",
        lastTouchedChapter: 1,
        progressMarkers: [],
      },
    ],
    ideaEntries: [],
    workingNotes: [],
    structureBeats: [],
    sceneCards: [],
    chapters: [
      {
        id: "chapter-1",
        number: 1,
        title: "The Cistern Oath",
        purpose: "Lucius hides the temple ledger with Baruch before dawn.",
        povCharacterId: "lucius",
        currentBeat: "He swears Baruch to secrecy and must recover the ledger after dark.",
        targetWordCount: 3000,
        keyBeats: ["Hide the scroll"],
        requiredInclusions: ["Temple ledger", "Baruch"],
        forbiddenElements: [],
        desiredMood: "Urgent",
        sceneList: [],
        outline: "",
        draft:
          "Lucius pressed the temple ledger into Baruch's hands beside the cistern. \"Hide it until dark,\" he said, and Baruch swore that no zealot would see it.",
        notes: "",
        status: "COMPLETE",
        wordCount: 0,
        summaries: [
          {
            id: "summary-1",
            kind: "CORE",
            summary: "Lucius hides the temple ledger with Baruch in a cistern and must recover it after dark.",
            bridgeText: "Carry forward Baruch, the cistern, and the hidden temple ledger.",
            emotionalTone: "Urgent",
            unresolvedQuestions: [],
          },
        ],
      },
      {
        id: "chapter-2",
        number: 2,
        title: "Dust Before Noon",
        purpose: "Lucius tries to pass as a merchant while the market riots.",
        povCharacterId: "lucius",
        currentBeat: "He bargains for bread while the city grows more dangerous.",
        targetWordCount: 3000,
        keyBeats: ["Bread riot"],
        requiredInclusions: ["Temple ledger", "Baruch"],
        forbiddenElements: [],
        desiredMood: "Claustrophobic",
        sceneList: [],
        outline: "Stay in the market.",
        draft:
          "The dust rolled through the market and Lucius haggled for a scrap of bread while the crowd screamed around the well. He kept his head down and thought only of getting back to his room before dusk.",
        notes: "",
        status: "DRAFTING",
        wordCount: 0,
        summaries: [],
      },
    ],
    longTermMemoryItems: [],
    shortTermMemoryItems: [],
    continuityIssues: [],
    assistRuns: [],
  };
}

describe("story analysis helpers", () => {
  it("does not mark a plot thread as active from broad background overlap alone", () => {
    const thread: PlotThreadRecord = {
      id: "thread-1",
      title: "Lucius's mission to infiltrate Jerusalem",
      summary: "Lucius gathers intelligence inside the city.",
      status: "ACTIVE",
      heat: 4,
      promisedPayoff: "He will deliver the right weakness to Titus.",
      lastTouchedChapter: 2,
      progressMarkers: [],
    };

    const weakSignal = detectPlotThreadSignal(
      thread,
      "Jerusalem groaned beneath siege while Lucius searched for shelter and cursed the dust.",
    );
    const strongSignal = detectPlotThreadSignal(
      thread,
      "Lucius resumed his mission to infiltrate Jerusalem by bribing a gate runner and mapping the guard rotations for Titus.",
    );

    expect(weakSignal.touched).toBe(false);
    expect(strongSignal.touched).toBe(true);
  });
});

describe("continuity rule checks", () => {
  it("flags dropped planned elements that vanish from the manuscript", () => {
    const project = makeProject();

    const issues = runContinuityRuleChecks(project, "chapter-2", project.chapters[1].draft, "CHAPTER");
    const titles = issues.map((issue) => issue.title);

    expect(titles).toContain("Required inclusion disappears from the chapter");
  });
});
