import { describe, expect, it } from "vitest";

import { buildContextPackage, extractMemoryFromDraft } from "@/lib/memory";
import type { ProjectWorkspace } from "@/types/storyforge";

function makeProject(): ProjectWorkspace {
  return {
    id: "project-1",
    title: "Test Project",
    slug: "test-project",
    premise: "A writer balances control and collaboration.",
    oneLineHook: "A novelist stress-tests an AI writing studio.",
    availableSeriesNames: ["The Draft Engine"],
    series: {
      id: "series-1",
      name: "The Draft Engine",
      slug: "the-draft-engine",
      description: "",
      books: [
        {
          projectId: "project-1",
          title: "Test Project",
          slug: "test-project",
          premise: "A writer balances control and collaboration.",
          oneLineHook: "A novelist stress-tests an AI writing studio.",
          seriesOrder: 2,
          chapterCount: 2,
        },
      ],
      sharedCharacterNames: ["Mara Quill"],
      sharedLocationNames: ["Night Office"],
      sharedPlotThreadTitles: ["Can Mara trust the tool?"],
    },
    seriesCanonicalAnchors: [
      "Series character from Book 1: Mara Quill - writer under pressure with a guarded voice.",
      "Series arc from Book 1: Can Mara trust the tool? - collaboration remains unresolved.",
    ],
    bookSettings: {
      authorName: "",
      seriesName: "The Draft Engine",
      seriesOrder: 2,
      genre: "Speculative fiction",
      tone: "Tense and lucid",
      audience: "Adult",
      themes: ["trust", "control"],
      pointOfView: "Third person limited",
      tense: "Past tense",
      targetChapterLength: 2200,
      targetBookLength: 85000,
      storyBrief: "Mara wants help without losing authorship.",
      plotDirection: "Escalate pressure while preserving agency.",
      pacingNotes: "Open in motion.",
      romanceLevel: 1,
      darknessLevel: 3,
      proseStyle: "Clear and vivid",
      comparableTitles: ["Dark Matter"],
    },
    styleProfile: {
      guidanceIntensity: "STRONG",
      proseDensity: 3,
      pacing: 4,
      darkness: 3,
      romanceIntensity: 1,
      humorLevel: 2,
      actionFrequency: 3,
      mysteryDensity: 4,
      dialogueDescriptionRatio: 6,
      literaryCommercialBalance: 7,
      aestheticGuide: "Rain, monitors, midnight focus.",
      styleGuide: "Favor specificity and momentum.",
      voiceRules: ["End scenes with pressure."],
    },
    generationPresets: [],
    characters: [
      {
        id: "char-1",
        name: "Mara Quill",
        role: "Writer",
        archetype: "Driven skeptic",
        summary: "A novelist who wants control.",
        goal: "Finish the book.",
        fear: "Losing her voice.",
        secret: "She likes being surprised.",
        wound: "A previous draft failed.",
        quirks: ["Counts revisions out loud"],
        notes: "",
        tags: ["writer"],
        povEligible: true,
        quickProfile: {
          age: "34",
          profession: "Writer",
          placeOfLiving: "Brooklyn",
          accent: "neutral American",
          speechPattern: "precise / guarded",
        },
        dossier: {
          basicIdentity: {
            fullName: "Mara Quill",
            nicknames: [],
            age: "34",
            dateOfBirth: "",
            gender: "",
            culturalBackground: "",
            nationality: "",
            currentResidence: "Brooklyn",
            placeOfOrigin: "",
            beliefSystem: "",
            maritalStatus: "",
            familyStatus: "",
          },
          lifePosition: {
            profession: "Writer",
            workplace: "",
            roleTitle: "",
            socialClass: "",
            educationLevel: "",
            trainingBackground: "",
            militaryBackground: "",
            criminalRecord: "",
            politicalOrientation: "",
            reputation: "",
          },
          personalityBehavior: {
            coreTraits: ["driven"],
            virtues: [],
            flaws: [],
            emotionalTendencies: "",
            socialConfidence: "",
            introExtroStyle: "",
            conflictStyle: "",
            decisionMaking: "",
            projectedImage: "",
            trueNature: "",
            hiddenSelf: "",
            embarrassmentTriggers: "",
            angerTriggers: "",
            comfortSources: "",
            fearTriggers: "",
            coreValues: "",
          },
          motivationStory: {
            shortTermGoal: "",
            longTermGoal: "Finish the book.",
            needVsWant: "",
            internalConflict: "",
            externalConflict: "",
            wound: "A previous draft failed.",
            secrets: ["She likes being surprised."],
            stakesIfFail: "",
            arcDirection: "",
            storyRole: "Writer",
            relationshipToMainConflict: "",
          },
          speechLanguage: {
            accent: "neutral American",
            dialect: "",
            nativeLanguage: "English",
            otherLanguages: [],
            fluencyLevels: "",
            formalityLevel: "",
            vocabularyLevel: "",
            educationInSpeech: "",
            sentenceLength: "",
            directness: "",
            pointStyle: "",
            descriptors: [],
            repeatedPhrases: [],
            favoriteExpressions: [],
            swearingLevel: "",
            rhythm: "",
            emotionalShifts: "",
            angrySpeech: "",
            scaredSpeech: "",
            lyingSpeech: "",
            persuasiveSpeech: "",
            superiorSpeech: "",
            inferiorSpeech: "",
            lovedOnesSpeech: "",
            avoidedTopics: "",
            commonMisunderstandings: "",
          },
          bodyPresence: {
            physicalDescription: "",
            build: "",
            clothingStyle: "",
            grooming: "",
            distinguishingFeatures: [],
            posture: "",
            movementStyle: "",
            eyeContact: "",
            habitsTics: [],
            roomEntry: "",
            presenceFeel: "",
          },
          relationshipDynamics: {
            friends: [],
            enemies: [],
            rivals: [],
            loversExes: [],
            family: [],
            mentors: [],
            subordinatesSuperiors: [],
            trustLevels: "",
            hiddenLoyalties: "",
            unspokenTensions: "",
            powerDynamics: "",
          },
          freeTextCore: "Mara wants control but secretly wants surprise too.",
        },
        currentState: {
          currentKnowledge: "",
          unknowns: "",
          emotionalState: "Focused",
          physicalCondition: "",
          loyalties: "",
          recentChanges: "",
          continuityRisks: "",
          lastMeaningfulAppearance: "",
          lastMeaningfulAppearanceChapter: 2,
        },
        customFields: [],
        pinnedFields: [],
      },
    ],
    relationships: [],
    locations: [],
    factions: [],
    timelineEvents: [],
    plotThreads: [
      {
        id: "thread-1",
        title: "Can Mara trust the tool?",
        summary: "She keeps testing the line between collaboration and surrender.",
        status: "ACTIVE",
        heat: 5,
        promisedPayoff: "A working collaboration model.",
        lastTouchedChapter: 2,
        progressMarkers: [],
      },
      {
        id: "thread-2",
        title: "Unrelated thread",
        summary: "Low-priority background pressure.",
        status: "ACTIVE",
        heat: 1,
        promisedPayoff: "",
        lastTouchedChapter: 1,
        progressMarkers: [],
      },
    ],
    chapters: [
      {
        id: "chapter-1",
        number: 1,
        title: "Opening Pressure",
        purpose: "Introduce the test.",
        povCharacterId: "char-1",
        currentBeat: "Mara commits to the experiment.",
        targetWordCount: 2200,
        keyBeats: ["Setup"],
        requiredInclusions: ["Night Office"],
        forbiddenElements: [],
        desiredMood: "Focused",
        sceneList: [],
        outline: "",
        draft: "Mara begins the test.",
        notes: "",
        status: "COMPLETE",
        wordCount: 4,
        summaries: [
          {
            id: "summary-1",
            kind: "CORE",
            summary: "Mara starts testing StoryForge under pressure.",
            bridgeText: "",
            emotionalTone: "Focused",
            unresolvedQuestions: ["Can she trust the system?"],
          },
        ],
      },
      {
        id: "chapter-2",
        number: 2,
        title: "Pressure Test",
        purpose: "Show Mara using StoryForge across the full spectrum.",
        povCharacterId: "char-1",
        currentBeat: "She drafts alone, then asks for help when the scene stalls.",
        targetWordCount: 2200,
        keyBeats: ["Solo writing", "Inline assist", "Continuity pass"],
        requiredInclusions: ["Night Office", "Trust"],
        forbiddenElements: ["Instant mastery"],
        desiredMood: "Focused, tense, slightly intimate with the work",
        sceneList: ["Opening draft"],
        outline: "Mara drafts, requests help, and decides what kind of collaborator StoryForge can be.",
        draft:
          "Mara stared at the blinking cursor until it felt like a dare. She wrote the first sentence anyway. The room seemed to narrow around the work as soon as she asked for help and wondered whether she could trust the system without surrendering control.",
        notes: "",
        status: "DRAFTING",
        wordCount: 29,
        summaries: [],
      },
    ],
    longTermMemoryItems: [
      {
        id: "lt-1",
        title: "Mara tests collaboration boundaries",
        content: "Mara wants help without surrendering authorship.",
        category: "CHARACTER",
        tags: ["trust", "control", "writer"],
        relevanceScore: 0.9,
        durabilityScore: 0.92,
        status: "ACTIVE",
        promotionReason: "Core arc material.",
        relatedChapterId: "chapter-1",
        relatedCharacterIds: ["char-1"],
        relatedLocationIds: [],
        relatedPlotThreadIds: ["thread-1"],
      },
      {
        id: "lt-2",
        title: "Background item",
        content: "Unrelated background memory.",
        category: "WORLD_RULE",
        tags: ["background"],
        relevanceScore: 0.2,
        durabilityScore: 0.3,
        status: "ACTIVE",
        promotionReason: "",
        relatedChapterId: null,
        relatedCharacterIds: [],
        relatedLocationIds: [],
        relatedPlotThreadIds: [],
      },
    ],
    shortTermMemoryItems: [
      {
        id: "st-1",
        title: "Recent emotional tone",
        content: "Focused, tense, slightly intimate with the work.",
        category: "EMOTION",
        tags: ["tone", "recent"],
        relevanceScore: 0.8,
        durabilityScore: 0.3,
        status: "CANDIDATE",
        promotionReason: "Useful bridge for the next chapter.",
        relatedChapterId: "chapter-1",
        relatedCharacterIds: ["char-1"],
        relatedLocationIds: [],
        relatedPlotThreadIds: ["thread-1"],
      },
    ],
    continuityIssues: [
      {
        id: "issue-1",
        chapterId: "chapter-2",
        severity: "MEDIUM",
        confidence: 0.7,
        checkMode: "CHAPTER",
        issueType: "Dropped thread",
        title: "Follow through on the trust question",
        description: "The draft should keep the trust conflict visible.",
        explanation: "The draft stops foregrounding the trust conflict.",
        suggestedContext: "Show Mara making a guarded but deliberate choice.",
        relatedEntity: "Mara",
        affectedElements: ["trust", "chapter-2"],
        status: "OPEN",
      },
    ],
    assistRuns: [],
  };
}

describe("memory helpers", () => {
  it("builds a compact context package from the most relevant memory", () => {
    const project = makeProject();
    const context = buildContextPackage(project, "chapter-2");

    expect(context.projectBrief).toContain("help without losing authorship");
    expect(context.previousChapterSummary).toContain("starts testing StoryForge");
    expect(context.chapterBlueprint[0]).toContain("Chapter 2");
    expect(context.seriesContext[0]).toContain("Series");
    expect(context.storyBibleContext.some((line) => line.includes("Character dossier: Mara Quill"))).toBe(true);
    expect(context.storySkeletonContext).toEqual([]);
    expect(context.relevantLongTermMemory[0]?.id).toBe("lt-1");
    expect(context.recentShortTermMemory[0]?.id).toBe("st-1");
    expect(context.activePlotThreads[0]?.id).toBe("thread-1");
    expect(context.continuityConstraints).toHaveLength(1);
    expect(context.tokenEstimate).toBeGreaterThan(0);
  });

  it("extracts durable and short-term chapter memory candidates", () => {
    const project = makeProject();
    const extraction = extractMemoryFromDraft(project, "chapter-2");

    expect(extraction.summary).toContain("Mara stared at the blinking cursor");
    expect(extraction.emotionalTone).toContain("Focused");
    expect(
      extraction.candidates.some((candidate) => candidate.classification === "long-term durable fact"),
    ).toBe(true);
    expect(
      extraction.candidates.some((candidate) => candidate.classification === "short-term temporary fact"),
    ).toBe(true);
    expect(
      extraction.candidates.some((candidate) => candidate.classification === "unresolved thread"),
    ).toBe(true);
    expect(
      extraction.candidates.some((candidate) => (candidate.relatedCharacterIds ?? []).includes("char-1")),
    ).toBe(true);
    expect(
      extraction.candidates.some((candidate) => (candidate.relatedPlotThreadIds ?? []).includes("thread-1")),
    ).toBe(true);
  });
});
